#!/bin/sh
i=0
_prefix() {
	num="$1"
	case "$num" in
		0) echo "B" ;;
		1) echo "KB" ;;
		2) echo "MB" ;;
		3) echo "GB" ;;
	esac
}
_shorten() {
	num="$1"
	[ "$num" -gt 999 ] && { num="$(( num / 1024))" ;
	i=$(( i +1 )) ;
	_shorten "$num";} || { p=$(_prefix "$i");
		echo "$num" "$p";}
}

case "$2" in
 d) rawdown=$(cat /sys/class/net/"$1"/statistics/rx_bytes) && _shorten "$rawdown" ;;
 u) rawup=$(cat /sys/class/net/"$1"/statistics/tx_bytes) && _shorten "$rawup" ;;
esac
